### ISSUE TITLE
[BUG] Closing an opened locker gives null ref in Interactable_OnInteraction prefix

### ISSUE THREAD

**Issue by Ven0maus** [Ven0maus/SOD.Common#17]
**Describe the bug**
```csharp
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SOD.Common.Patches.InteractionControllerPatches.Interactable_OnInteraction.Prefix(Interactable __instance, SimpleActionArgs& __state, InteractionAction action, Actor who)
   at DMD<Interactable::OnInteraction>(Interactable this, InteractionAction action, Actor who, Boolean allowDelays, Single additionalDelay)
   at (il2cpp -> managed) OnInteraction(IntPtr , IntPtr , IntPtr , Byte , Single , Il2CppMethodInfo* )
```

**Reproduction scenario**
Close a locker or opened safe door, or open a keypad door.

**Expected behavior**
No error message shown

**Additional context**
Found a random opened locker in a dinner, closing it gives me this error.
Also happens when closing an opened safe door.

**Comment by Ven0maus** [comment]
I solved the null reference errors on bugfix-interaction branch, but after doing some testing it appears the re-use code part is actually never entered, what is its purpose and can it be removed?

**Comment by Ven0maus** [comment]
Null references fixed, new hotfix released

**Comment by ReveredRedHood** [comment]
Regarding the errors in SOD.Common, I tracked these down as causes:
- Picking up key from ground: ActionController.TakeKey, ActionController.AIPickItemUpFromFloor
- OnLongActionCompleted
- Closing safe, locker door. not breaker box door though
- Elevator starts/stops moving
- Unlocking code door

**Comment by ReveredRedHood** [comment]
Ah, never mind, I did a diff and see that all features should still be present.
