### ISSUE TITLE
[FEATURE] Add ChainLoader util to detect the presence of another mod

### ISSUE THREAD

**Issue by ReveredRedHood** [Ven0maus/SOD.Common#18]
**Introduction**
Based on suggestion from Arsonide on Discord

> I'm overridding Player.IsTrespassing to do the above, and I feel like lots of mods are going to want to change the trespassing behavior. I think it would be a good candidate for something in SODCommon that different mods can hook into to add new trespassing behaviors. 
> 
> Here's my current code: https://pastebin.com/Y1ct0Tei
> 
> I have to do a reverse patch over the base Human.IsTrespassing method, I copied most of the existing Player.IsTrespassing code into this and I return false at the end so this is totally overriding Player.IsTrespassing. The actual return value is the __result ref. My bit is the isCrunchingDatabase block, and I imagine other modders may want additional blocks there.

**Description of the feature**
- [Detecting loaded plugins](https://github.com/BepInEx/BepInEx/discussions/320#discussioncomment-1495741)
- [Change PluginController to use this, if it doesn't already](https://harmony.pardeike.net/articles/priorities.html)
- [BepInEx SoftDependency](https://docs.bepinex.dev/v6.0.0-pre.1/api/BepInEx.BepInDependency.DependencyFlags.html)
- [Checking for existing Harmony patches](https://harmony.pardeike.net/articles/basics.html#checking-for-existing-patches)

**Feature usage**
Would allow mod authors to check for the presence of a mod. Would be useful for cases where methods have been patched for already-released mods, patching them, etc.

**Dependencies and Prerequisites**
Does this feature require any new dependencies? **No**

**Implementation details**
As extension methods or static methods in Lib, or as a change to PluginController

**Comment by Ven0maus** [comment]
Implemented in V1.1.8
