### ISSUE TITLE
Life and Living applies item cost increases to vendors multiple times [BUG]

### ISSUE THREAD

**Issue by PatchyDragon** [Ven0maus/SOD.Common#22]
**Describe the bug**
While using Life and Living in a longer play session, I noticed that as I played, the prices of things were climbing up the longer I played. Things that were reasonable before were quite rapidly becoming inordinately expensive (300 for a Kola, 1k for a Truncheon!)

Restarting returned the game to normal, and costs were once again what I'd set them to previously. After some experimentation, I realized that the costs were increasing each time I reloaded the game, with no real ceiling in sight. This is probably not intended behavior.

**Reproduction scenario**
Enable SOD.LifeandLiving and its dependencies
Set LifeAndLiving.ItemPrice, PercentageValueIncrease to a non-zero positive number
Start game
Locate any vendor (Snack machine, drinks, weapon locker, medical-...)
Observe prices, they should be higher than vanilla, as expected
Save game, reload game without exiting SoD
Observe prices again, they should be more expensive than previously now.

**Expected behavior**
Percentage increases would be applied once at game startup, and not reapply on each reload.

**Additional context**
This would be an interesting way to punish save scumming, but I keep having to reload due to bugs with eating, drinking, or sometimes just NPCs getting stuck in a loop. (One NPC got in a loop of trying to lock a door that somehow had no lock, another once just kept pulling the fire alarm every 5 seconds.)

**Comment by Ven0maus** [comment]
Patched in v1.0.5, thanks @PatchyDragon
