### ISSUE TITLE
[FEATURE] Add pause and resume utilities and event handlers

### ISSUE THREAD

**Issue by ReveredRedHood** [Ven0maus/SOD.Common#3]
Here's the idea I had for how I might add these.

Events:
- Lib.Pause.OnGamePaused(PauseSource)
- Lib.Pause.OnGameResumed(UnpauseSource)

Methods (calling these will result in the PauseSource or UnpauseSource being "Script"):
- Lib.Pause.ResumeGame()
- Lib.Pause.PauseGame()

Enum:
PauseSource = { CaseBoard, Inventory, MainMenu, Save, Script }

**Comment by ReveredRedHood** [comment]
For simplicity, I'll start with the implementation without the PauseSource and UnpauseSource. Also, we can remove UnpauseSource and have one enum instead:
PauseSource = { CaseBoard, Inventory, MainMenu, Save, Script }

**Comment by Ven0maus** [comment]
Scrapped the PauseSource feature as there were too many entries in the game where the pause flow can trigger from.
