### ISSUE TITLE
[BUG] Crash when SODStockMarket is used together with EvidenceLinkModifiers

### ISSUE THREAD

**Issue by Neko14789** [Ven0maus/SOD.Common#33]
**Describe the bug**
The game crashes when your mod (SODStockMarket) and EvidenceLinkModifiers are installed together

**Reproduction scenario**
Install both Mods at the same time

**Expected behavior**
Game starts and does not crash

**Additional context**
It looks like your mod also throws some other errors in console, even when not installed together with EvidenceLinkModifiers

**Comment by Ven0maus** [comment]
Please provide more information, any [Error] exceptions you encounter in the logs.
Also provide an actual reproduction scenario up until the crash happens so I can investigate.

I just ran the game with just SOD.Common and those 2 mods and it works fine.
New game, and loading existing game all works fine.
No crashes, no errors.
The warnings shown by StockMarket can be ignored, as they don't break anything.

**Comment by Neko14789** [comment]
Sorry, it seems like the crashing when starting the game is a result of more mods together than only this two. I have found out that a mod named "Winmin" contributed to this crash, but when I only test these 3 mods it works. It seems that some of my 35 installed mods crash when used in a special way together. Not sure how to easily find the issue. Sorry for raising an issue :(
