### ISSUE TITLE
[FEATURE] [StockMarket] Link murder case events to company stocks.

### ISSUE THREAD

**Issue by Orionox** [Ven0maus/SOD.Common#35]
**Introduction**
It would be amazing if a murder happening in X building that is owned by Y company resulted in a dip in stocks. OR If person X who works for Y company is cheated on, the company can take a dip as well. Basically, making the cases affect the stock market would be amazing. As a much more advanced feature, having stocks be a reason for murder could be cool. You search a perps computer and find they have shorted the company they keep killing people at or something like that. OR you find that your perp has a 100 stocks in a company that took a nose dive and they blame the company for losing them money so they've started targeting employees of that company..... etc.

**Comment by Ven0maus** [comment]
There are currently some stocks based on the in game companies but that's only a relative small portion of them.
It could indeed be interesting to have cases impact these stocks, I might indeed look into adding some kind of interaction here.
In the current version only the player can own stocks.

**Comment by Ven0maus** [comment]
Implemented, will be part of stockmarket v2.0.8
Release is planned somewhere end of this week.
