### ISSUE TITLE
[BUG] OnAfterLoad occurs during the loading screen

### ISSUE THREAD

**Issue by ReveredRedHood** [Ven0maus/SOD.Common#4]
MurderController.StartGame might be a better patch target... but idk if that one is disabled during certain Sandbox scenarios.

**Comment by Ven0maus** [comment]
It was originally the prefix  (before) and the postfix (after) but the method its hooked to just starts the task (or handled through update method with stages).
I suppose it does make more sense to trigger this specific event after the load is done.
